#!/bin/bash   
MACHINE=$1

EINSTEIN_URL="ubuntu@ec2-13-234-184-74.ap-south-1.compute.amazonaws.com"

if [ "$MACHINE" == "einstein" ]; then
	ssh -i "~/secret/aws/aws-key.pem"  $EINSTEIN_URL
else
	echo "Server '$MACHINE' not known"
fi
