#!/bin/bash
MACHINE=$1

EINSTEIN_URL="ec2-13-234-184-74.ap-south-1.compute.amazonaws.com"
AWS_KEY="~/secret/aws/aws-key.pem"

CASH_URL="ec2-18-185-217-168.eu-central-1.compute.amazonaws.com"
MERCURY_URL="ec2-3-248-17-208.eu-west-1.compute.amazonaws.com"
MERCURY2_URL="ec2-54-72-61-24.eu-west-1.compute.amazonaws.com"
COBAIN_URL="ec2-52-215-179-47.eu-west-1.compute.amazonaws.com"


if [ "$MACHINE" == "einstein" ]; then
	sshfs \
    -o follow_symlinks \
    -o transform_symlinks \
    -o TCPKeepAlive=yes \
    -o ServerAliveCountMax=2 \
    -o ServerAliveInterval=5 \
    -o IdentityFile=$AWS_KEY \
    ubuntu@$EINSTEIN_URL:/home/ubuntu/  \
    ~/$MACHINE/
elif [ "$MACHINE" == "cash" ]; then
	sshfs \
    -o follow_symlinks \
    -o transform_symlinks \
    -o TCPKeepAlive=yes \
    -o ServerAliveCountMax=2 \
    -o ServerAliveInterval=5 \
    -o IdentityFile="~/secret/aws_cashreader/aws-frankfurt.pem" \
    ubuntu@$CASH_URL:/home/ubuntu/  \
    ~/$MACHINE/
elif [ "$MACHINE" == "mercury" ]; then
	sshfs \
    -o follow_symlinks \
    -o transform_symlinks \
    -o TCPKeepAlive=yes \
    -o ServerAliveCountMax=2 \
    -o ServerAliveInterval=5 \
    -o IdentityFile="~/secret/aws_biano/tomas.prinda--public-key.pem" \
    ubuntu@$MERCURY_URL:/home/ubuntu/  \
    ~/$MACHINE/
elif [ "$MACHINE" == "mercury2" ]; then
	sshfs \
    -o follow_symlinks \
    -o transform_symlinks \
    -o TCPKeepAlive=yes \
    -o ServerAliveCountMax=2 \
    -o ServerAliveInterval=5 \
    -o IdentityFile="~/secret/aws_biano/tomas.prinda--public-key.pem" \
    ubuntu@$MERCURY2_URL:/home/ubuntu/  \
    ~/$MACHINE/
elif [ "$MACHINE" == "cobain" ]; then
	sshfs \
    -o follow_symlinks \
    -o transform_symlinks \
    -o TCPKeepAlive=yes \
    -o ServerAliveCountMax=2 \
    -o ServerAliveInterval=5 \
    -o IdentityFile="~/secret/aws_biano/tomas.prinda--public-key.pem" \
    ubuntu@$COBAIN_URL:/home/ubuntu/  \
    ~/$MACHINE/
else
	echo "Server '$MACHINE' not known"
fi
