#!/bin/bash   
MACHINE=$1

EINSTEIN_URL="ubuntu@ec2-13-234-184-74.ap-south-1.compute.amazonaws.com"
DAVINCI_URL="ec2-user@ec2-13-210-195-219.ap-southeast-2.compute.amazonaws.com"

if [ "$MACHINE" == "einstein" ]; then
	ssh -i "~/secret/aws/aws-key.pem"  $EINSTEIN_URL
elif [ "$MACHINE" == "davinci" ]; then
	ssh -i "~/secret/aws/aws-key-ap-south-1.pem" $DAVINCI_URL
else
	echo "Server '$MACHINE' not known"
fi
